Repository atlp-rwanda/ecommerce-app-predators-bn, pull requests merged in 2023-04, with the labels that each got.

#9 Chore #37 setup environment variables
  .env.example
  .gitignore
  app.js
  package-lock.json
  package.json
  server.js
Labels: Need Reviews

#7 Ch- setup- docker- 26
  .dockerignore
  Dockerfile
  docker-compose.dev.yml
  docker-compose.prod.yml
  docker-compose.yml
  package-lock.json
Labels: Need Reviews

#6 Ch setup continuous integration #24
  .eslintrc.cjs
  .github/workflows/ci.yml
  .github/workflows/node.js.yml
  README.md
  app.js
  database/seeders/20230329224756-demo-user.cjs
  docs/swagger.js
  jest.config.js
  package-lock.json
  package.json
  routes/welcome.js
  src/app.js
  src/controller/deleteMeController.js
  src/database/config/config.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403191535-create-product.cjs
  src/database/migrations/20230403191841-create-carts.cjs
  src/database/migrations/20230403192058-create-cart-items.cjs
  src/database/migrations/20230403192329-create-roles.cjs
  src/database/models/cart_items.js
  src/database/models/carts.js
  src/database/models/index.cjs
  src/database/models/product.js
  src/database/models/roles.js
  src/database/models/user.js
  src/database/seeders/20230403195829-User.cjs
  src/database/seeders/20230403202838-Carts.cjs
  src/database/seeders/20230403202849-Products.cjs
  src/database/seeders/20230403202953-Cart_Items.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
  src/middleware/deleteMe.js
  src/middleware/i18next.js
  src/routes/welcome.js
  src/server.js
  tests/sample.js
Labels: Need Reviews

#20 feat(sign-in-with-google): create the Google SignIn feature #11
  .github/workflows/node.js.yml
  .sequelizerc
  README.md
  docs/GoogleDoc.yml
  docs/authSignUp.yml
  docs/disable.yml
  docs/setRole.yml
  docs/swagger.js
  docs/userdoc.yml
  package-lock.json
  package.json
  src/app.js
  src/config/swagger.js
  src/controller/authController.js
  src/controller/deleteMeController.js
  src/database/config/config.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403191535-create-product.cjs
  src/database/migrations/20230403191841-create-carts.cjs
  src/database/migrations/20230403192058-create-cart-items.cjs
  src/database/migrations/20230403192329-create-roles.cjs
  src/database/models/index.cjs
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20230403195829-User.cjs
  src/database/seeders/20230403202838-Carts.cjs
  src/database/seeders/20230403202849-Products.cjs
  src/database/seeders/20230403202953-Cart_Items.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/welcome.js
  src/server.js
  src/services/role.services.js
  src/services/user.services.js
  src/utils/hashPassword.js
  src/utils/jwt.js
  src/utils/passport.js
  src/utils/sendEmail.js
  src/utils/userToken.js
Labels: Need Reviews

#19 #32 Feature: Reset password
  src/app.js
  src/controller/authController.js
  src/controller/cartController.js
  src/middleware/auth.middleware.js
  src/routes/authRoutes.js
  src/routes/cartRoute.js
  src/services/user.services.js
  src/utils/jwt.js
  src/utils/sendEmail.js
Labels: Need Reviews

#26 #3 feature: build signup endpoint
  README.md
  docs/authSignUp.yml
  package-lock.json
  package.json
  src/app.js
  src/config/swagger.js
  src/controller/authController.js
  src/database/models/user.js
  src/database/seeders/20230403202838-Carts.cjs
  src/database/seeders/20230403202849-Products.cjs
  src/database/seeders/20230403202953-Cart_Items.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
Labels: Need Reviews

#21 #5 Feature: register vendors
  .eslintrc.cjs
  README.md
  docs/venderSignup.yml
  package-lock.json
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/disable.acount.controller.js
  src/controller/vendorController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403192329-create-roles.cjs
  src/database/models/user.js
  src/database/seeders/20230403195829-User.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/welcome.js
  src/server.js
  src/services/role.services.js
  src/utils/jwt.js
  src/utils/passport.js
Labels: Need Reviews

#16 #13(feature): signIn with email and password
  .github/workflows/node.js.yml
  .gitignore
  README.md
  docs/adminDoc.yml
  package-lock.json
  src/controller/authController.js
  src/database/models/index.js
  src/database/seeders/20230403203144-ROLEs.cjs
  src/middleware/loginMiddeleware.js
  src/routes/authRoutes.js
Labels: Need Reviews

#23 README file updated
  .gitignore
  README.md
  dist/app.js
  dist/config/swagger.js
  dist/controller/authController.js
  dist/controller/cartController.js
  dist/controller/productController.js
  dist/controller/profileController.js
  dist/database/config/config.js
  dist/database/migrations/20230403191345-create-user.js
  dist/database/migrations/20230403191535-create-product.js
  dist/database/migrations/20230403191841-create-carts.js
  dist/database/migrations/20230403192058-create-cart-items.js
  dist/database/migrations/20230403192329-create-roles.js
  dist/database/models/cart_items.js
  dist/database/models/carts.js
  dist/database/models/index.js
  dist/database/models/product.js
  dist/database/models/roles.js
  dist/database/models/user.js
  dist/database/seeders/20230403195829-User.js
  dist/database/seeders/20230403202838-Carts.js
  dist/database/seeders/20230403202849-Products.js
  dist/database/seeders/20230403202953-Cart_Items.js
  dist/database/seeders/20230403203144-ROLEs.js
  dist/middleware/auth.middleware.js
  dist/middleware/deleteMe.js
  dist/middleware/i18next.js
  dist/middleware/roles.js
  dist/routes/authRoutes.js
  dist/routes/cartRoute.js
  dist/routes/welcome.js
  dist/server.js
  dist/services/role.services.js
  dist/services/user.services.js
  dist/utils/hashPassword.js
  dist/utils/jwt.js
  dist/utils/passport.js
  dist/utils/sendEmail.js
  dist/utils/userToken.js
  docs/disable.yml
  docs/setRole.yml
  package-lock.json
  src/app.js
  src/controller/authController.js
  src/controller/disable.acount.controller.js
  src/database/config/config.js
  src/database/seeders/20230403195829-User.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/services/user.services.js
Labels: Need Reviews

#17 #9 Enable 2-Factor-Authentication
  .env.example
  .github/workflows/node.js.yml
  .gitignore
  config/development.cjs
  config/production.cjs
  config/test.cjs
  docs/2factor.yml
  docs/swagger.js
  package-lock.json
  package.json
  server.js
  src/app.js
  src/controller/authController.js
  src/controller/otpAuthController.js
  src/controller/vendorController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403192329-create-roles.cjs
  src/database/models/user.js
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/otpAuthRoute.js
  src/server.js
  src/services/confirmationEmail.js
  src/utils/hashPassword.js
Labels: Need Reviews

#37 Ft fix bugs from develop
  Dockerfile
  README.md
  config/development.cjs
  config/production.cjs
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/otpAuthController.js
  src/controller/productController.js
  src/controller/profileController.js
  src/controller/vendorController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403191535-create-product.cjs
  src/database/migrations/20230403191841-create-carts.cjs
  src/database/migrations/20230403192058-create-cart-items.cjs
  src/database/models/cart_items.js
  src/database/models/carts.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/seeders/20230403202849-Products.cjs
  src/middleware/roles.js
  src/routes/ProductRoutes.js
  src/routes/authRoutes.js
  src/services/user.services.js
  src/utils/jwt.js
Labels: Top priority

#33 #14 feature: create product registration endpoint
  src/app.js
  src/controller/authController.js
  src/controller/prodController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230403191535-create-product.cjs
  src/database/models/product.js
  src/database/models/user.js
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/prodRoute.js
Labels: Top priority

#34 #17 feature(search)A user able to search a product
  src/controller/search.controller.js
  src/routes/ProductRoutes.js
  src/routes/authRoutes.js
Labels: Ready for Merge

#30 #15 retrieve specific item
  src/controller/productController.js
  src/database/migrations/20230403192058-create-cart-items.cjs
  src/database/migrations/20230403192329-create-roles.cjs
  src/database/seeders/20230403202838-Carts.cjs
  src/database/seeders/20230403202849-Products.cjs
  src/database/seeders/20230403202953-Cart_Items.cjs
  src/database/seeders/20230403203144-ROLEs.cjs
  src/routes/authRoutes.js
Labels: Need Reviews

#31 #29 Enable Product-Listing
  docs/productListing.yml
  package.json
  src/controller/productController.js
  src/controller/productListingController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/models/roles.js
  src/database/seeders/20230403202849-Products.cjs
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/productListingRoute.js
  src/services/user.services.js
Labels: Need Reviews

#42 #27 feature: recommend product to a buyer
  .gitignore
  package-lock.json
  src/app.js
  src/controller/categoryController.js
  src/controller/productController.js
  src/controller/search.controller.js
  src/controller/vendorController.js
  src/database/migrations/20230427115144-create-category.cjs
  src/database/models/category.js
  src/database/models/product.js
  src/routes/authRoutes.js
  src/routes/categoryRoutes.js
  src/services/user.services.js
Labels: Need Reviews

#36 wishlist-feature-18
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/search.controller.js
  src/controller/wishlistController.js
  src/database/migrations/20230403191841-create-carts.cjs
  src/database/migrations/20230425181236-create-wishlist.cjs
  src/database/models/Roles.js
  src/database/models/product.js
  src/database/models/user.js
  src/database/models/wishlist.js
  src/middleware/roles.js
  src/routes/authRoutes.js
  src/routes/wishlistRoute.js
  src/services/user.services.js
Labels: Top priority

#43 fixed develop
  src/controller/wishlistController.js
  src/database/models/product.js
  src/database/models/wishlist.js
  src/database/seeders/20230403202838-Carts.cjs
  src/routes/authRoutes.js
Labels: Top priority
