Repository atlp-rwanda/ecommerce-app-predators-bn, pull requests merged in 2023-05, with the labels that each got.

#50 #00 fixed routes
  src/app.js
  src/controller/search.controller.js
  src/controller/wishlistController.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/models/user.js
  src/routes/ProductRoutes.js
  src/routes/authRoutes.js
  src/routes/prodRoute.js
  src/routes/productListingRoute.js
  src/routes/wishlistRoute.js
Labels: Top priority

#46 # 19 Feature: add to cart
  .sequelizerc
  package-lock.json
  src/app.js
  src/controller/authController.js
  src/controller/cartController.js
  src/database/migrations/20230403192058-create-cart-items.cjs
  src/database/models/cart_items.js
  src/database/models/index.js
  src/database/seeders/20230403195829-User.cjs
  src/middleware/auth.middleware.js
  src/routes/authRoutes.js
  src/routes/cartRoutes.js
  src/services/cartItem.services.js
  src/services/product.services.js
  src/services/user.services.js
  src/utils/userToken.js
Labels: Top priority

#55 # 21 Feature: update cart items
  .nyc_output/b625b0ef-284d-4cc9-a64f-be786a1d1e24.json
  .nyc_output/processinfo/b625b0ef-284d-4cc9-a64f-be786a1d1e24.json
  .nyc_output/processinfo/index.json
  config/test.cjs
  package-lock.json
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/cartController.js
  src/controller/search.controller.js
  src/database/models/cart_items.js
  src/database/models/index.js
  src/database/models/user.js
  src/middleware/auth.middleware.js
  src/middleware/roles.js
  src/routes/ProductRoutes.js
  src/routes/cartRoutes.js
  src/routes/categoryRoutes.js
  src/routes/prodRoute.js
  src/services/cartItem.services.js
  src/services/product.services.js
  tests/.mocharc.cjs
  tests/cart.test.js
  tests/sample.js
  tests/sample.test.js
Labels: Top priority

#60 #23 feature clear cart items
  src/controller/cartController.js
  src/routes/cartRoutes.js
  src/services/cartItem.services.js
Labels: Need Reviews, Ready for Merge

#48 # 20 Feature: view cart items
  package-lock.json
  src/controller/authController.js
  src/controller/cartController.js
  src/database/models/cart_items.js
  src/middleware/roles.js
  src/routes/prodRoute.js
  src/services/cartItem.services.js
  src/services/product.services.js
  tests/cart.test.js
  tests/product.test.js
Labels: Top priority

#47 #5 feature: add in-app and email notifications
  src/controller/cartController.js
  src/controller/checkoutController.js
  src/controller/wishlistController.js
Labels: Need Reviews

#45 #1 ft(discount-coupon):Seller CRUD Operation functionalities
  src/app.js
  src/controller/discountCouponController.js
  src/database/config/config.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230430093423-create-discount-coupon.cjs
  src/database/models/discountcoupon.js
  src/database/models/index.js
  src/routes/cartRoutes.js
  src/routes/discountCouponRoute.js
  src/utils/passport.js
  tests/Product.test.js
  tests/cart.test.js
  tests/product.test.js
Labels: Top priority

#66 #9 feature(Buyer should be able to provide a review)
  src/app.js
  src/controller/cartController.js
  src/controller/productController.js
  src/controller/reviewController.js
  src/database/config/config.js
  src/database/migrations/20230403191345-create-user.cjs
  src/database/migrations/20230510065300-create-review.cjs
  src/database/models/product.js
  src/database/models/review.js
  src/database/seeders/20230403195829-User.cjs
  src/routes/authRoutes.js
  src/routes/reviewRoute.js
  src/services/product.services.js
  tests/cart.test.js
  tests/vendor.test.js
Labels: Need Reviews

#59 #3 Create Checkout Flow
  .github/workflows/node.js.yml
  .gitignore
  config/development.cjs
  config/production.cjs
  config/test.cjs
  package-lock.json
  package.json
  src/app.js
  src/controller/checkoutController.js
  src/controller/otpAuthController.js
  src/controller/productListingController.js
  src/database/migrations/20230502193542-create-order.cjs
  src/database/models/index.js
  src/database/models/order.js
  src/database/models/product.js
  src/database/seeders/20230403195829-User.cjs
  src/database/seeders/20230403202849-Products.cjs
  src/middleware/roles.js
  src/routes/ProductRoutes.js
  src/routes/notificationRoutes.js
  src/routes/otpAuthRoute.js
  tests/Product.test.js
  tests/cart.test.js
  tests/checkout.test.js
  tests/login.js
  tests/otp.test.js
  tests/product.listing.test.js
  tests/vendor.test.js
Labels: Ready for Merge

#53 #2 feature: create payment processing endpoint
  .eslintrc.cjs
  package-lock.json
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/checkoutController.js
  src/controller/paymentController.js
  src/controller/prodController.js
  src/database/config/config.js
  src/routes/ProductRoutes.js
  src/routes/orderRoutes.js
  src/routes/paymentsRouter.js
  src/routes/prodRoute.js
  src/services/event.services.js
Labels: Need Reviews, Ready for Merge

#63 Fixing develop
  .github/workflows/node.js.yml
  config/development.cjs
  config/production.cjs
  locales/en/translation.json
  locales/fr/translation.json
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/checkoutController.js
  src/controller/productController.js
  src/controller/profileController.js
  src/controller/wishlistController.js
  src/database/migrations/20230403191535-create-product.cjs
  src/database/migrations/20230425181236-create-wishlist.cjs
  src/database/models/product.js
  src/database/models/user.js
  src/database/models/wishlist.js
  src/middleware/i18next.js
  src/routes/authRoutes.js
  src/services/product.services.js
  tests/Product.test.js
  tests/cart.test.js
  tests/checkout.test.js
  tests/otp.test.js
  tests/product.listing.test.js
  vercel.json
Labels: Need Reviews

#69 translations-of-our-App
  .nyc_output/00ec88cc-0ff1-46c4-88aa-8387b311720f.json
  .nyc_output/b625b0ef-284d-4cc9-a64f-be786a1d1e24.json
  .nyc_output/processinfo/00ec88cc-0ff1-46c4-88aa-8387b311720f.json
  .nyc_output/processinfo/b625b0ef-284d-4cc9-a64f-be786a1d1e24.json
  .nyc_output/processinfo/index.json
  README.md
  config/development.cjs
  locales/en/translation.json
  locales/fr/translation.json
  package-lock.json
  package.json
  src/app.js
  src/controller/checkoutController.js
  src/controller/wishlistController.js
  src/database/migrations/20230425181236-create-wishlist.cjs
  src/database/migrations/20230427115144-create-category.cjs
  src/database/migrations/20230517223317-create-socket-connection.cjs
  src/database/migrations/20230518100019-create-room.cjs
  src/database/migrations/20230518100243-create-room-socket-connection.cjs
  src/database/migrations/20230524210936-create-chat.cjs
  src/database/models/wishlist.js
  src/middleware/roles.js
  tests/cart.test.js
  tests/login.js
Labels: Need Reviews

#71 #11 features: configure public live chat
  package-lock.json
  package.json
  src/app.js
  src/controller/authController.js
  src/controller/chatController.js
  src/database/migrations/20230517223317-create-socket-connection.cjs
  src/database/migrations/20230518100019-create-room.cjs
  src/database/migrations/20230518100243-create-room-socket-connection.cjs
  src/database/migrations/20230524210936-create-chat.cjs
  src/database/models/chat.js
  src/database/models/room.js
  src/database/models/roomsocketconnection.js
  src/database/models/socketconnection.js
  src/database/models/user.js
  src/public/CSS/chatRoom.css
  src/public/CSS/index.css
  src/public/CSS/rooms.css
  src/public/JS/chatRoom.js
  src/public/JS/index.js
  src/public/JS/rooms.js
  src/routes/chatRoutes.js
  src/services/chatsDb.services.js
  src/utils/chatServer.js
  src/views/chatRoom.ejs
  src/views/index.ejs
  src/views/rooms.ejs
  tests/cart.test.js
  tests/chat.test.js
Labels: Need Reviews

#70 Testing coverage
  .coveralls.yml
  .github/workflows/node.js.yml
  .mocharc.cjs
  .nyc_output/f1df5a1f-e139-46df-b7b9-49b2b36476b8.json
  .nyc_output/processinfo/f1df5a1f-e139-46df-b7b9-49b2b36476b8.json
  .nyc_output/processinfo/index.json
  README.md
  c8.config.js
  locales/en/translation.json
  locales/fr/translation.json
  package-lock.json
  package.json
  tests/vendor.test.js
Labels: Need Reviews
